[book]
authors = ["Sped0n"]
language = "en"
multilingual = false
src = "src"
title = "data-structure"

[preprocessor.katex]
after = ["links"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
